### ISSUE TITLE
柱状图点击以后实现，shadow的效果

### ISSUE THREAD

**Issue by Gamehu** [apache/incubator-echarts#10684] opened 2019-06-17 03:30 UTC
### What problem does this feature solve?
当柱状体值特别小时，点击之后，看不到点击效果，想通过点击后在所在栅格加上类似shadow的效果，告诉用户其实是选中了该柱状图

### What does the proposed API look like?

                myChart.dispatchAction({
type: 'showShadow',
seriesIndex:0
})

**Comment by Ovilia** [comment] 2019-06-17 03:56
Duplicate of #10685

**Closed by Ovilia** 2019-06-17 03:56 UTC
Labels: new-feature, pending, waiting-for-help
