### ISSUE TITLE
用了axisLabel 属性，横坐标的最后一项会加粗

### ISSUE THREAD

**Issue by 695750180** [apache/incubator-echarts#10445] opened 2019-05-13 01:39 UTC
### Version
4.1.0-release

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xUk6_ZbrEF&v=1](https://gallery.echartsjs.com/editor.html?c=xUk6_ZbrEF&v=1)

### Steps to reproduce
打开链接就能重现

### What is expected?
最后一项与前面几项横坐标的文字格式一样，不要加粗

### What is actually happening?
最后一项的横坐标会被加粗

**Comment by Ovilia** [comment] 2019-05-13 02:38
Duplicate of #10304

**Closed by Ovilia** 2019-05-13 02:38 UTC
Labels: bug, pending, waiting-for-help
