### ISSUE TITLE
CSS property page-break-inside: avoid not working

### ISSUE THREAD

**Issue by iamtekson** [apache/incubator-echarts#12402] opened 2020-04-08 05:33 UTC
### Version
4.7.0

### Reproduction link
[https://ibb.co/x8SYJfx](https://ibb.co/x8SYJfx)

### Steps to reproduce
I have generated largen number of bar charts using this library. Now I want to print them all using `ctrl p`. I added CSS properties `page-break-inside: avoid` in my parent `div`. But it is still breaking

### What is expected?
I want my bar chart to include in only one page. Not break the page for a single chart

### What is actually happening?
My chart is still appearing in two pages.

**Comment by pissang** [comment] 2020-04-11 06:35
Sorry, but I think the issue is not related to ECharts

**Comment by iamtekson** [comment] 2020-04-11 06:39
But in other contents like `image`, `text`, `table`, it works fine. While I try to avoid the page break in `echarts` it avoids the rule (page is not breaking and graph appearing in two pages). Do you have any idea?

**Comment by Ovilia** [comment] 2020-04-16 03:18
Make sure your CSS selector works on the canvas inside and if it still doesn't work, search for canvas page breaking solutions. I'm closing this because it's not related to ECharts.

**Closed** 2020-04-16 03:18 UTC
Labels: not-related
