### ISSUE TITLE
在2K分辨率下，热力图还是会有随机出现的灰色虚线

### ISSUE THREAD

**Issue by rollYouth** [apache/incubator-echarts#12519] opened 2020-04-28 12:00 UTC
### Version
4.7.0

### Steps to reproduce
https://www.echartsjs.com/examples/zh/editor.html?c=heatmap-large
官方示例上也有

### What is expected?
希望大大们帮忙看一下怎么处理

### What is actually happening?
现在在2k屏上还是有灰色的虚线， 1920*1080的则是正常的
<img width="453" alt="heatmap_bug" src="https://user-images.githubusercontent.com/56584514/80484835-f3fa9800-898a-11ea-9e24-47eb19ceebc7.png">

**Comment by 100pah** [comment] 2020-04-30 11:39
Similar to #11975.
Fixed and will be released in 4.8.0 soon.

**Comment by Ovilia** [comment] 2020-05-25 08:56
Duplicate of #11975. Fixed in 4.8.0.

**Closed by Ovilia** 2020-05-25 08:56 UTC
Labels: duplicate
