### ISSUE TITLE
Android environment screenshots must turn off hardware acceleration

### ISSUE THREAD

**Issue by TobyCheung** [apache/incubator-echarts#9702] opened 2019-01-08 02:26 UTC
## Issue Type

- [x ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

Android environment screenshots must turn off hardware acceleration.

### Expected Behavior

Open the hardware acceleration of the Android device and intercept the chart.

### Current Behavior

Android environment screenshots must turn off hardware acceleration.

### Online Example

import Echarts from 'native-echarts';
import ViewShot from 'react-native-view-shot';

let chart = (
    <Echarts option={option} height={scaleSize(500)} width={screenW}/>
);

let priceTrend = (
    <View style={styles.priceTrend} collapsable={false}>
        <SectionHeader
            title={'价格走势'}
            rightView={
                <ScrollableTabBar
                    ref={(scrollableTabBar) => this.scrollableTabBar = scrollableTabBar}
                    tabs={this.priceTrendTabs}
                    activeTab={this.trendRange}
                    activeTextColor={'#24b5fe'}
                    inactiveTextColor={'#4c4c4c'}
                    fontSize={scaleSize(28)}
                    onTabClick={(index) => {
                        this._onTrendTabClick(index)
                    }}
                    containerWidth={screenW - 135}
                    containerHeight={scaleSize(93)}
                    scrollEnabled={false}
                />
            }
        />
        <Line/>
        {this.state.trendData && this.state.trendData !== '' ?
            chart:
            (this.state.loadingTrendData ? <LoadMoreView showText={false}/>:
                <View style={{flex: 1, justifyContent:'center', alignItems:'center'}}>
                    <Image source={Images.price.table_no_data} style={{width:scaleSize(1080*0.65), height:scaleSize(565*0.65)}}/>
                </View>
            )
        }
    </View>
)

let shareBoard = (
	<ScrollView style={{width:screenW + realSize(80), height: 0.5}} >
		<ViewShot
                  ref={r => this.shareView = r}
                  options={{format:"jpg", quality:1.0}}
              >
			<View
				style={{
					width:screenW + realSize(80),
					alignItems: 'center',
					paddingLeft:realSize(40),
					paddingRight:realSize(40),
					backgroundColor:'#ebf2fd'
				}}
			>
				<Image source={Images.information.message_share01}
					   style={{width:realSize(270), height:realSize(65), marginTop:realSize(60), marginBottom:realSize(60)}}/>
				<View style={{
					width:screenW,
					paddingTop:scaleSize(20),
					paddingBottom:scaleSize(20),
					borderRadius:scaleSize(20),
					borderWidth: scaleSize(4),
					borderColor:'#e5ebf6',
					backgroundColor:'#fafcff'
					// backgroundColor:'#f4f5f7'
				}}>
					<SectionHeader title={this.productType}/>
					<Line/>
					{topViewShare}
					<Line style={{marginTop: scaleSize(15)}} width={screenW - scaleSize(80)} height={realSize(1)}
						  color={'#f2f2f2'}
						  leftSpace={scaleSize(40)}/>
					{priceView}
					<Line style={{marginTop: scaleSize(10)}} width={screenW - scaleSize(80)} height={realSize(1)}
						  color={'#f2f2f2'}
						  leftSpace={scaleSize(40)}/>
					{priceView1}
					{priceTrend}
				</View>
				<View style={{
					width:screenW,
					height:scaleSize(220),
					backgroundColor:'#fafcff',
					marginTop:scaleSize(60),
					marginBottom:scaleSize(40),
					borderRadius:scaleSize(20),
					borderWidth: scaleSize(4),
					borderColor:'#e5ebf6',
					flexDirection: 'row',
					alignItems: 'center',
					justifyContent: 'space-between',
					paddingLeft: scaleSize(20),
					paddingRight: scaleSize(20),
				}}>
					<Image source={Images.information.message_share03} style={{width:scaleSize(508), height:scaleSize(140)}}/>
					<Image source={Images.information.message_qrCode} style={{width:scaleSize(140), height:scaleSize(140)}}/>
				</View>
				<Image source={Images.information.message_share04}
					   style={{width:scaleSize(600), height:scaleSize(32), marginBottom:scaleSize(40)}}
					   resizeMode={'contain'}/>
			</View>
		</ViewShot>
          </ScrollView>
);

_shareIOS = () => {
	this.shareView.capture()
           .then(uri => {
               console.log('uri:'+uri);
			let imgUrl = '';
			if (isIOS) {
				imgUrl = uri;
			} else {
				imgUrl = uri.replace('file:///', '/');
			}
			let text = '';
			let img = imgUrl;
			let title = '';
			let url = '';
			let list = [0, 2, 3, 32, 1];

			UMShareUtil.shareboard(text, img, url, title, list, (code, message) => {
				// Alert.alert(message);
			});
           })
		.catch(
			(error) => alert(error)
		);
};

## Anything Else We Need to Know

In my Android app (accurately the ReactNative project) I need to share the screenshots of the eCharts page. If I don't turn off the Android device hardware acceleration, the captured part of the chart will be blank. After the hardware acceleration is turned off, I can capture the chart. The problem is that turning off hardware acceleration will cause other pages in the application to use the webView display to slide slowly, and I would like to ask if there is a way to open the hardware acceleration of the Android device and intercept the chart. Thank you.

## Environment

- ECharts version；ECharts 版本: 0.4.0

- [x] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：Android system

**Comment by Ovilia** [comment] 2019-01-10 09:39
Duplicate of #9731

**Closed by Ovilia** 2019-01-10 09:39 UTC
Labels: missing-info
