### ISSUE TITLE
setOption doen't update graphic elements

### ISSUE THREAD

**Issue by eniaclyl** [apache/incubator-echarts#11120] opened 2019-08-28 03:32 UTC
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xcUz8mQAdp&v=1](https://gallery.echartsjs.com/editor.html?c=xcUz8mQAdp&v=1)

### Steps to reproduce
单击直线可以正确删除，单击圆无法删除

### What is expected?
单击圆也可以正确删除

### What is actually happening?
单击圆无法删除

---
如果改为如下代码会删除真个坐标系，这是错误的效果
myChart.setOption({
            graphic: [{
                elements: []
            }]
        }, true);

**Comment by eniaclyl** [comment] 2019-08-28 03:41
@Ovilia @yufeng04 大佬们，删除图元和删除直线的行为不一样，是不是bug导致的呀？怎么解决这个问题，求教！！！急急急！！！！

**Comment by Ovilia** [comment] 2019-08-28 04:08
This seems to be a bug. 
Before being fixed, you can use [this method](https://gallery.echartsjs.com/editor.html?c=xcUz8mQAdp&v=3) to walkaround.

**Comment by eniaclyl** [comment] 2019-08-28 04:11
@Ovilia 请问什么时候发布新版本，在下个版本会修复这个bug吗

**Comment by eniaclyl** [comment] 2019-08-28 04:13
@Ovilia 大佬 你这个办法我不能用，因为我的图有缩放的功能 ，如果myChart.setOption(option, true);使用这个办法会导致工具栏的还原功能失效

**Comment by Ovilia** [comment] 2019-08-28 08:25
v4.4.0 is planned to be fixed before 30th Sep. But the actual release date may depend on many other factors.

**Comment by eniaclyl** [comment] 2019-08-28 08:38
@Ovilia 好的多谢，顺便问下，我之前提的那个lines在cartesian2d模式下缩放后无法裁剪的bug也能在4.4.0版本修复吗？

**Comment by yufeng04** [comment] 2019-08-28 15:26
#11119

**Comment by Ovilia** [comment] 2019-08-28 15:34
@eniaclyl Which one?
Not sure we still have time for that in this version.

**Comment by eniaclyl** [comment] 2019-08-29 00:43
@Ovilia 好的 多谢

**Comment by pissang** [comment] 2019-09-02 11:42
Hi @eniaclyl . You need to use '$actoin: delete' to delete the elements. Check https://echarts.apache.org/en/option.html#graphic.elements-group.$action

**Comment by eniaclyl** [comment] 2019-09-03 02:19
@pissang  In other words, is this not a bug? Is this the correct usage?

**Comment by pissang** [comment] 2019-09-03 07:13
@eniaclyl  It's not a bug. By default the option be merged.

**Comment by eniaclyl** [comment] 2019-09-03 07:17
@pissang thank you

**Closed** 2019-09-03 07:39 UTC
Labels: support
