### ISSUE TITLE
calendar not displaying ranges properly

### ISSUE THREAD

**Issue by macthestack** [apache/incubator-echarts#11677] opened 2019-11-19 09:24 UTC
### Version
4.5.0

### Reproduction link
[https://codesandbox.io/s/wizardly-pascal-jcom3](https://codesandbox.io/s/wizardly-pascal-jcom3)

### Steps to reproduce

see link

I can only reproduce it with UK timezone set

### What is expected?
A contiguous calendar.

### What is actually happening?
Days jumbled all over.

![Screenshot 2019-11-20 at 17 03 43](https://user-images.githubusercontent.com/10058934/69260436-cd545c00-0bb7-11ea-95be-ebf3c9ddcf79.png)

**Comment by macthestack** [comment] 2019-11-20 17:06
Added images since the bug seem to depend on what timezone you are in which may not be obvious.

**Comment by Ovilia** [comment] 2019-11-21 03:19
Reproduced with UK timezone.

**Comment by macthestack** [comment] 2020-01-03 10:42
Any updates on this?

**Comment by Ovilia** [comment] 2020-01-17 08:25
@macthestack Sorry. Let me put it to a higher priority.

**Comment by macthestack** [comment] 2020-01-17 09:43
Thank you.

**Comment by yafengstark** [comment] 2020-01-18 13:11
The situation gets wrong result because of DST.

**Comment by 100pah** [comment] 2020-04-20 20:41
Fixed in #12172

**Closed by 100pah** 2020-04-20 20:41 UTC
Labels: bug, en, timezone
