### ISSUE TITLE
legend custom icon deformation

### ISSUE THREAD

**Issue by JeffesJiang** [apache/incubator-echarts#12777] opened 2020-06-09 07:21 UTC
### Version
4.8.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xY58XMB6n3&v=2](https://gallery.echartsjs.com/editor.html?c=xY58XMB6n3&v=2)

### Steps to reproduce
chart dom size changed，legend custom icon deformation

### What is expected?
No deformation

### What is actually happening?
deformation

---
because use icon path do not change color，and add fill in path can cause legend  collapse
 
 symbolKeepAspect attribute only supported path icon

**Comment by plainheart** [comment] 2020-06-09 07:59
Seems to be a bug. Thank you for reporting!

**Comment by JeffesJiang** [comment] 2020-06-09 08:05
> Seems to be a bug. Thank you for reporting!

Because I closed the click event, in fact, when I triggered the click, it would be deformed

**Comment by plainheart** [comment] 2020-06-12 05:32
By now, I think it may be not a bug. Except using `path` type, if you have to take `image` as the type of legend, you'd better set [`itemWidth`](https://echarts.apache.org/zh/option.html#legend.itemWidth) and [`itemHeight`](https://echarts.apache.org/zh/option.html#legend.itemHeight) as real with and height of the image.
See https://gallery.echartsjs.com/editor.html?c=xY58XMB6n3&v=3

**Comment by JeffesJiang** [comment] 2020-06-12 05:37
> 到目前为止，我认为这可能不是错误。除了使用`path`类型，如果你要`image`像传说中的类型，你最好设定[`itemWidth`](https://echarts.apache.org/zh/option.html#legend.itemWidth)，并[`itemHeight`](https://echarts.apache.org/zh/option.html#legend.itemHeight)与真正的和高度的图像。
> 参见https://gallery.echartsjs.com/editor.html?c=xY58XMB6n3&v=3

Thank you for your reply. I may fall into a mistake. I think we will get the width and height by default and define them. I didn't notice that the size of the image can be specified.

**Comment by Ovilia** [comment] 2020-06-12 09:09
@JeffesJiang If your problem has been solved and this is not a bug, please consider closing the issue. Thanks.

**Closed** 2020-06-12 09:10 UTC
Labels: bug, waiting-for: author
