### ISSUE TITLE
radar.axisLabel.formatter needs indicator parameter

### ISSUE THREAD

**Issue by lahvey** [apache/incubator-echarts#11532] opened 2019-10-31 02:20 UTC
current options:
```js
formatter: '{value} kg',
formatter: function (value, index) {
}
```

Each indicator has its own formatter method, for example we need to show 5kg, 10cm.

这个问题在`radar.name.formatter`也出现过，已经被修复，不知道其他地方还有没有类似问题：
```js
formatter: function (value, indicator) {
    if (indicator.index === 1) return `${value}kg`;
    return `${value}cm`;
}
```

**Comment by Ovilia** [comment] 2019-11-01 03:01
Duplicate of #11323.

**Closed by Ovilia** 2019-11-01 03:01 UTC
