### ISSUE TITLE
Minor problems with sankey.d.ts

### ISSUE THREAD

**Issue by softwords** [apache/incubator-echarts#12763] opened 2020-06-07 05:23 UTC
### Version
4.8.0

### Steps to reproduce
Some problems in typescript definitions `@types\echarts` (v4.6.1) for sankey series cause compilation errors in typescript:

`name` is missing - this causes problems even when not working with sankey chart.

`nodeAlign` is missing

`links` is defined as a single link object - should be an array of such objects

### What is expected?
These snippets should compile:

1)

```
let option:echarts:EChartOption = { };
let seriesNames = option.series.map(s => s.name);
```
2) 

```
let series: echarts.EChartOption.SeriesSankey = {
		type: 'sankey',
		focusNodeAdjacency: 'allEdges',
		data: [{
			name: 'a'
		}, {
			name: 'b'
		}, {
			name: 'a1'
		}, {
			name: 'a2'
		}, {
			name: 'b1'
		}, {
			name: 'c'
		}],
		links: [{
			source: 'a',
			target: 'a1',
			value: 5
		}, {
			source: 'a',
			target: 'a2',
			value: 3
		}, {
			source: 'b',
			target: 'b1',
			value: 8
		}, {
			source: 'a',
			target: 'b1',
			value: 3
		}, {
			source: 'b1',
			target: 'a1',
			value: 1
		}, {
			source: 'b1',
			target: 'c',
			value: 2
		}]
};
```

### What is actually happening?
1) 

compilation error: 

```
Property 'name' does not exist on type 'Series'.
  Property 'name' does not exist on type 'SeriesSankey'.
```

2)

compilation error:

```
error TS2559: Type '{ source: string; target: string; value: number; }[]' 
has no properties in common with type 
'{ source?: string; target?: string; value?: number; lineStyle?: { color?: string; opacity?: 
number; curveness?: number; shadowBlur?: number; shadowColor?: string; shadowOffsetX?: number; shadowOffsetY?: number; }; emphasis?: { ...; }; }'.
```

---
Not sure if this is the right place to report this, since the issue is in the echarts .d.ts files, not echarts itself....

**Comment by Ovilia** [comment] 2020-06-08 02:26
If this is caused by the type definition under DefinitelyTyped, a simple fix would be changing it to as any. You may also make a pull request to that project if you wish.

**Comment by softwords** [comment] 2020-06-08 12:27
@Ovilia thankyou for your prompt reply. I have created a PR in DefinitelyTyped as you suggested,

**Comment by Ovilia** [comment] 2020-06-12 02:20
Thanks! I will close the issue here. If you have more questions with the PR, we can discuss there.

**Closed by Ovilia** 2020-06-12 02:20 UTC
Labels: en, support, third-party, waiting-for: community
