### ISSUE TITLE
http://www.webcarpenter.com/blog/93-Using-D3js-to-Visualize-a-Binary-Tree

### ISSUE THREAD

**Issue by rajpatelukyahoo** [apache/incubator-echarts#9822] opened 2019-01-22 21:22 UTC
Has anyone attempted to recreate this tree in echarts?
d3 code......

/* D3 Tree */
/* Copyright 2013 Peter Cook (@prcweb); Licensed MIT */

// Tree configuration
var branches = [];
var seed = {i: 0, x: 420, y: 600, a: 0, l: 130, d:0}; // a = angle, l = length, d = depth
var da = 0.5; // Angle delta
var dl = 0.8; // Length delta (factor)
var ar = 0.7; // Randomness
var maxDepth = 10;

// Tree creation functions
function branch(b) {
	var end = endPt(b), daR, newB;

	branches.push(b);

	if (b.d === maxDepth)
		return;

	// Left branch
	daR = ar * Math.random() - ar * 0.5;
	newB = {
		i: branches.length,
		x: end.x,
		y: end.y,
		a: b.a - da + daR,
		l: b.l * dl,
		d: b.d + 1,
		parent: b.i
	};
	branch(newB);

	// Right branch
	daR = ar * Math.random() - ar * 0.5;
	newB = {
		i: branches.length,
		x: end.x, 
		y: end.y, 
		a: b.a + da + daR, 
		l: b.l * dl, 
		d: b.d + 1,
		parent: b.i
	};
	branch(newB);
}

function regenerate(initialise) {
	branches = [];
	branch(seed);
	initialise ? create() : update();
}

function endPt(b) {
	// Return endpoint of branch
	var x = b.x + b.l * Math.sin( b.a );
	var y = b.y - b.l * Math.cos( b.a );
	return {x: x, y: y};
}

// D3 functions
function x1(d) {return d.x;}
function y1(d) {return d.y;}
function x2(d) {return endPt(d).x;}
function y2(d) {return endPt(d).y;}
function highlightParents(d) {
	var colour = d3.event.type === 'mouseover' ? 'green' : '#777';
	var depth = d.d;
	for(var i = 0; i <= depth; i++) {
		d3.select('#id-'+parseInt(d.i)).style('stroke', colour);
		d = branches[d.parent];
	}	
}

function create() {
	d3.select('svg')
		.selectAll('line')
		.data(branches)
		.enter()
		.append('line')
		.attr('x1', x1)
		.attr('y1', y1)
		.attr('x2', x2)
		.attr('y2', y2)
		.style('stroke-width', function(d) {return parseInt(maxDepth + 1 - d.d) + 'px';})
		.attr('id', function(d) {return 'id-'+d.i;})
		.on('mouseover', highlightParents)
		.on('mouseout', highlightParents);
}

function update() {
	d3.select('svg')
		.selectAll('line')
		.data(branches)
		.transition()
		.attr('x1', x1)
		.attr('y1', y1)
		.attr('x2', x2)
		.attr('y2', y2);
}

d3.selectAll('.regenerate')
	.on('click', regenerate);

regenerate(true);

## Issue Type

- [x ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by ClemMakesApps** [comment] 2019-01-22 21:38
@rajpatelukyahoo could you provide a codepen - so that it's easier to reproduce?

**Comment by deqingli** [comment] 2019-09-03 03:33
hi @rajpatelukyahoo, since you haven't response this issue for a long time, I will close it, hoping you understand.

**Closed by deqingli** 2019-09-03 03:33 UTC
Labels: waiting-for: author
