### ISSUE TITLE
请问如何实现highcharts.js中对数折线图中的minortickinterval功能？

### ISSUE THREAD

**Issue by losper** [apache/incubator-echarts#9703] opened 2019-01-08 03:56 UTC
## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

请问如何实现highcharts.js中对数折线图中的minortickinterval功能？

我需要一个对数折线图，并提供minortickinterval功能。在文档中发现有对数数轴的功能，但没有minortickinterval属性。请问哪些属性可以完成这个功能？

### Expected Behavior

https://www.hcharts.cn/demo/highcharts/line-log-axis

### Online Example
https://www.hcharts.cn/demo/highcharts/line-log-axis

## Topics
- [x] Legend

## Environment

- ECharts version；ECharts 版本: 无要求

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment] 2019-01-08 09:47
Duplicate of #7840

**Closed by Ovilia** 2019-01-08 09:47 UTC
