### ISSUE TITLE
TypeError: api.coord is not a function Errror

### ISSUE THREAD

**Issue by yycyeung** [apache/incubator-echarts#12539] opened 2020-04-29 12:08 UTC
### Version
3.8.5

### Steps to reproduce
draw polygons like https://echarts.apache.org/examples/en/editor.html?c=map-polygon

### What is expected?
many beautiful polygons in my map

### What is actually happening?
"TypeError: api.coord is not a function" appears

---
i found out that there is no coord function in my api object (no coordSys in param as well)
I search online, and people suggest me to import echarts/extension/bmap
The problem is i am using the leaflet extension but not bmap, I would like to know is it possible to draw polygon in leaflet or it is necessary to include bmap in my work?

"echarts": "^3.8.5",
"echarts-leaflet": "^1.1.0",
"leaflet": "^1.6.0"

btw....I cannot open the echarts gallery https://gallery.echartsjs.com/ is it run by u guys?

Thank you for your time ;) and Sorry if you feel like its not a bug...

**Comment by susiwen8** [comment] 2020-04-29 13:50
@yycyeung Have you tried the latest ECharts? Version 4.7?

**Comment by plainheart** [comment] 2020-04-29 13:50
A `coordinateSystem` in your case is required. If you want to use echarts in leaflet, you may need an echarts plugin for leaflet.  Within the example, it can draw polygons by using the [custom series](https://echarts.apache.org/en/option.html#series-custom) since it depends on the plugin [Extension for Baidu Map](https://github.com/apache/incubator-echarts/tree/master/extension/bmap) which is provided officially.
There may be no need to use bmap, you can search in Github with the keyword `leaflet-echarts` to pick one suitable for you.
BTW, I think the version you are using is too old, it's better to upgrade it to 4.x. :)

![image](https://user-images.githubusercontent.com/26999792/80602231-705faa80-8a61-11ea-808f-192ba908461e.png)

**Comment by yycyeung** [comment] 2020-05-04 01:40
> @yycyeung Have you tried the latest ECharts? Version 4.7?

Yesss. still got "prepareCustoms[coordSys.type] is not a function"

**Comment by yycyeung** [comment] 2020-05-04 01:41
> A `coordinateSystem` in your case is required. If you want to use echarts in leaflet, you may need an echarts plugin for leaflet. Within the example, it can draw polygons by using the [custom series](https://echarts.apache.org/en/option.html#series-custom) since it depends on the plugin [Extension for Baidu Map](https://github.com/apache/incubator-echarts/tree/master/extension/bmap) which is provided officially.
> There may be no need to use bmap, you can search in Github with the keyword `leaflet-echarts` to pick one suitable for you.
> BTW, I think the version you are using is too old, it's better to upgrade it to 4.x. :)
> 
> ![image](https://user-images.githubusercontent.com/26999792/80602231-705faa80-8a61-11ea-808f-192ba908461e.png)

yess. I use echarts-leaflet, the third one in the pic I updated the echarts to 4.X.X but still got "prepareCustoms[coordSys.type] is not a function"

**Comment by plainheart** [comment] 2020-05-04 03:00
@yycyeung OK! I have found this error is caused by the `echarts-leaflet` plugin since this plugin does not support custom series. I will give you some fixing suggestions later. :)

**Comment by yycyeung** [comment] 2020-05-04 03:05
> @yycyeung OK! I have found this error is caused by the `echarts-leaflet` plugin since this plugin does not support custom series. I will give you some fixing suggestions later. :)

great! thanks a lot

**Comment by plainheart** [comment] 2020-05-04 03:20
@yycyeung My pleasure.

**Fixing code**
```js
LeafletCoordSys.prototype.prepareCustoms = function (data) {
  var rect = this.getViewRect();
  return {
      coordSys: {
          type: 'leaflet',
          x: rect.x,
          y: rect.y,
          width: rect.width,
          height: rect.height
      },
      api: {
          coord: echarts.util.bind(this.dataToPoint, this),
          size: echarts.util.bind(dataToCoordSize, this)
      }
  };
};

function dataToCoordSize(dataSize, dataItem) {
    dataItem = dataItem || [0, 0];
    return echarts.util.map([0, 1], function (dimIdx) {
        var val = dataItem[dimIdx];
        var halfSize = dataSize[dimIdx] / 2;
        var p1 = [];
        var p2 = [];
        p1[dimIdx] = val - halfSize;
        p2[dimIdx] = val + halfSize;
        p1[1 - dimIdx] = p2[1 - dimIdx] = dataItem[1 - dimIdx];
        return Math.abs(this.dataToPoint(p1)[dimIdx] - this.dataToPoint(p2)[dimIdx]);
    }, this);
}
```

- Add codes above to the dist file `echarts-leaflet.js` after [line 87](https://github.com/gnijuohz/echarts-leaflet/blob/master/dist/echarts-leaflet.js#L87) or modify the source file and rebuild it.

- Rerun your project and we can see the expected result. (Maybe need to rebuild if you are using esModule)

![image](https://user-images.githubusercontent.com/26999792/80934022-c1242a00-8df8-11ea-8489-354eff6997cd.png)

**Comment by plainheart** [comment] 2020-05-04 03:28
BTW, we can also draw polygons with `leaflet` api and it's not necessary to use echarts to draw.
```js
var leaflet = myChart.getModel().getComponent('leaflet').getLeaflet();
var latlngs = [
    [39.53, 116.7],
    [36.03, 103.73],
    [27.87, 112.91],
    [28.01,120.65],
    [39.95, 119.57]
];
L.polygon(latlngs, { color: 'red' }).addTo(leaflet);
```

Also, that's our expected result.

![image](https://user-images.githubusercontent.com/26999792/80934321-40fec400-8dfa-11ea-8b48-f6a2f723b190.png)

**Comment by yycyeung** [comment] 2020-05-04 06:08
> BTW, we can also draw polygons with `leaflet` api and it's not necessary to use echarts to draw.
> 
> ```js
> var leaflet = myChart.getModel().getComponent('leaflet').getLeaflet();
> var latlngs = [
>     [39.53, 116.7],
>     [36.03, 103.73],
>     [27.87, 112.91],
>     [28.01, 120.65],
>     [39.95, 119.57]
> ];
> L.polygon(latlngs, { color: 'red' }).addTo(leaflet);
> ```
> 
> Also, that's our expected result.
> 
> ![image](https://user-images.githubusercontent.com/26999792/80934321-40fec400-8dfa-11ea-8b48-f6a2f723b190.png)

lol you are right, thanks a lot ;DDDDD

**Comment by Ovilia** [comment] 2020-05-06 04:59
@yycyeung If your problem has been solved, please close the issue.

**Closed** 2020-05-09 11:30 UTC
Labels: en, support, waiting-for: author
