### ISSUE TITLE
Stacked bars positioned out of the grid when datazoom toolbox feature is used

### ISSUE THREAD

**Issue by hamidhasnain** [apache/incubator-echarts#9237] opened 2018-10-16 07:54 UTC
https://jsfiddle.net/hmdhs/96cox2nz/

Echarts version: 4.2.0

Stacked bar graph when used with datazoom toolbox feature goes out of the grid. Without datazoom graph behaves as expected.

**Comment by deqingli** [comment] 2018-10-17 02:44
Thank for your feedback.

**Comment by Ovilia** [comment] 2018-10-26 04:51
Duplicate of #8935 .

**Closed by Ovilia** 2018-10-26 04:51 UTC
Labels: enhancement
