### ISSUE TITLE
echarts树图如何点击节点后的文字也能触发点击节点时所触发的事件？

### ISSUE THREAD

**Issue by huanledeniuduzi** [apache/incubator-echarts#12041] opened 2020-01-14 07:10 UTC
### Version
4.0.0

### Steps to reproduce
echarts.util.each(data.children, function(datum, index) {
index % 2 === 0 && (datum.collapsed = true);
});
myChart.setOption(option = {
tooltip: {
trigger: 'item',
triggerOn: 'mousemove'
},
series: [{
type: 'tree',
data: [data],
top: '1%',
left: '7%',
bottom: '1%',
right: '20%',
symbolSize: 7,
label: {
normal: {
position: 'left',
verticalAlign: 'middle',
align: 'right',
fontSize: 9
}
},
leaves: {
label: {
normal: {
position: 'right',
verticalAlign: 'middle',
align: 'left'
}
}
},
expandAndCollapse: true,
animationDuration: 550,
animationDurationUpdate: 750
}]
});

### What is expected?
点击节点后的文字也能实现点击节点的效果

### What is actually happening?
只有点击节点的时候才能触发收缩和展开的事件

**Comment by Ovilia** [comment] 2020-01-15 07:26
Duplicate of #9815.

**Closed by Ovilia** 2020-01-15 07:26 UTC
Labels: bug, pending, waiting-for: community
