### ISSUE TITLE
Toolbox data display abnormal while using dataset values

### ISSUE THREAD

**Issue by buliar** [apache/incubator-echarts#11546] opened 2019-11-01 07:07 UTC
<img width="1257" alt="WechatIMG131" src="https://user-images.githubusercontent.com/10826103/68008276-56632c00-fcb9-11e9-9a64-7a3eee9a974f.png">

**Comment by yufeng04** [comment] 2019-11-01 12:32
Toolbox data display normal in this [example](https://www.echartsjs.com/zh/tutorial.html#%E4%BD%BF%E7%94%A8%20dataset%20%E7%AE%A1%E7%90%86%E6%95%B0%E6%8D%AE). Maybe you should check your own code.

**Comment by buliar** [comment] 2019-11-05 00:50
hello @yufeng04 , I tried copy very simple toolbox options in this [example](https://www.echartsjs.com/examples/zh/editor.html?c=dataset-simple0), but dataView display NaN. Could you help me make it work fine?
I use the following toolbox options.
    toolbox: {
        show : true,
        feature : {
            dataView : {show: true, readOnly: false},
            magicType : {show: true, type: ['line', 'bar']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },

**Comment by Ovilia** [comment] 2019-11-05 03:22
Yes, this should be a bug. @buliar

**Comment by LianJilu** [comment] 2020-01-12 15:35
There is a error warning, this bug caused by using assembleSeriesWithCategoryAxis func, and dataset do not have y dimension, maybe i can fix it.
![image](https://user-images.githubusercontent.com/25577583/72221134-8e78cc00-3592-11ea-8cbc-fb34a143d353.png)

**Comment by Ovilia** [comment] 2020-03-02 03:07
Duplicate of #7533. This will be fixed in the next release.

**Closed** 2020-03-02 03:08 UTC
Labels: bug, difficulty: easy, duplicate, en, priority: normal
