### ISSUE TITLE
pie chart display abnormal when dimensions are numbers 

### ISSUE THREAD

**Issue by yangdanself** [apache/incubator-echarts#11662] opened 2019-11-18 03:08 UTC
### Version
4.5.0-rc.2

### Reproduction link
[https://jsfiddle.net/yangdanself/7ckm6rtg/4/](https://jsfiddle.net/yangdanself/7ckm6rtg/4/)

### Steps to reproduce
open the link you will see it

### What is expected?
surpport numeric dimensions

### What is actually happening?
pie chart display abnormal when dimensions are numbers

---
tooltip display abnormal when dimension is number '0'  in bar chart, maybe this happens in other charts when dimensions are numbers, please check it

**Comment by Ovilia** [comment] 2019-11-18 06:41
Duplicate of #11419, which is under fixing now. Please follow that issue instead. Thanks.

**Closed** 2019-11-18 06:41 UTC
Labels: bug, duplicate, en
