### ISSUE TITLE
Numerical display of scatter diagram

### ISSUE THREAD

**Issue by lzy560911** [apache/incubator-echarts#12028] opened 2020-01-13 07:45 UTC
### Version
4.6.0

### Reproduction link
[https://www.echartsjs.com/examples/zh/editor.html?c=effectScatter-bmap](https://www.echartsjs.com/examples/zh/editor.html?c=effectScatter-bmap)

### Steps to reproduce
When opening the scatter chart page, we will find that the value of the scatter chart shows the latitude of the location rather than the corresponding value

### What is expected?
The expected result is the value of the corresponding position

### What is actually happening?
The actual result is the dimension of the corresponding location

---
Open the scatter diagram instance page to find out the problem without specific scenarios

**Comment by Ovilia** [comment] 2020-01-13 10:40
Duplicate of #11528. It's under fixing.

**Closed** 2020-01-13 10:41 UTC
Labels: bug, duplicate, en
