### ISSUE TITLE
Bug with stack bar with min value

### ISSUE THREAD

**Issue by linwrui** [apache/incubator-echarts#11086] opened 2019-08-23 06:09 UTC
### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xj7nMfFWLh&v=1](https://gallery.echartsjs.com/editor.html?c=xj7nMfFWLh&v=1)

### Steps to reproduce
在堆积图中设置数值轴的最小值即可复现该BUG，并且在4.1.0之前的版本中未发现该问题，升级到4.2.1后出现的
配置信息：
```
app.title = '堆叠条形图';

option = {
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    legend: {
        data: ['直接访问', '邮件营销','联盟广告','视频广告','搜索引擎']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis:  {
        type: 'value',
        **min:300 // 设置这个值就会导致渲染异常，如果不设置最小值是正常的，并且在4.1.0之前的版本中未发现该问题**
    },
    yAxis: {
        type: 'category',
        data: ['周一','周二','周三','周四','周五','周六','周日']
    },
    series: [
        {
            name: '直接访问',
            type: 'bar',
            stack: '总量',
            label: {
                normal: {
                    show: true,
                    position: 'insideRight'
                }
            },
            data: [320, 302, 301, 334, 390, 330, 320]
        },
        {
            name: '邮件营销',
            type: 'bar',
            stack: '总量',
            label: {
                normal: {
                    show: true,
                    position: 'insideRight'
                }
            },
            data: [120, 132, 101, 134, 90, 230, 210]
        },
        {
            name: '联盟广告',
            type: 'bar',
            stack: '总量',
            label: {
                normal: {
                    show: true,
                    position: 'insideRight'
                }
            },
            data: [220, 182, 191, 234, 290, 330, 310]
        },
        {
            name: '视频广告',
            type: 'bar',
            stack: '总量',
            label: {
                normal: {
                    show: true,
                    position: 'insideRight'
                }
            },
            data: [150, 212, 201, 154, 190, 330, 410]
        },
        {
            name: '搜索引擎',
            type: 'bar',
            stack: '总量',
            label: {
                normal: {
                    show: true,
                    position: 'insideRight'
                }
            },
            data: [820, 832, 901, 934, 1290, 1330, 1320]
        }
    ]
};
```
### What is expected?
期望从最小值开始往上堆积

### What is actually happening?
图形错乱并且超出坐标轴范围

**Comment by smnbbrv** [comment] 2019-09-10 13:04
If it's helpful, in version 4.1.0 it works as intended

**Comment by pissang** [comment] 2019-09-19 05:34
Fixed in https://github.com/apache/incubator-echarts/commit/de98ef690ddfc0e608c7a0e9af4d6f7b30beb0fd

**Closed** 2019-09-20 02:14 UTC
Labels: bug
