### ISSUE TITLE
Treemap -SVG - long text labels and more lables in a block overlaps on another block  and labels.

### ISSUE THREAD

**Issue by Monali-ITT** [apache/incubator-echarts#11423] opened 2019-10-17 07:43 UTC
### Version
4.3.0

### Reproduction link
[https://jsfiddle.net/hemantss/jx6zwf7y/](https://jsfiddle.net/hemantss/jx6zwf7y/)

### Steps to reproduce
1. Create treemap with svg with long text in labels.
2. The output is displayed correctly. But long text labels in treemap blocks go out of blocks  Or overlap on another block.

### What is expected?
It should not overlap on other blocks.

### What is actually happening?
Text labels in treemap block go out of block  Or overlap on another block.

---
I have created issue for same problem. Treemap- SVG -Labels not fit in treemap blocks #10732.
I have tried with new version but same issue is reproduced. 
Can you please share working demo with new version?

https://github.com/apache/incubator-echarts/issues/10732

**Comment by Ovilia** [comment] 2019-10-17 08:01
Duplicate of #10732. Please follow that original issue.

**Closed by Ovilia** 2019-10-17 08:01 UTC
