### ISSUE TITLE
Don't preserve space for empty values on category axis

### ISSUE THREAD

**Issue by f-loris** [apache/incubator-echarts#11325] opened 2019-09-25 18:26 UTC
### What problem does this feature solve?
In my case I have different categories and multiple series (bar), where not every series has data for each category (i.e. some null values exist).  Currently, ECharts preserves the space for each category in each series. The goal would be to don't preserve space for null values, i.e. no leaks within a category. Therefore each category can be of a different length.

I haven't found a way to handle this with the existing functionality which ECharts provides.

**Currently:**
![image](https://user-images.githubusercontent.com/9257417/65628927-b982e400-dfd2-11e9-88b4-2130d937a286.png)

**Goal:**
![image](https://user-images.githubusercontent.com/9257417/65628683-3f525f80-dfd2-11e9-9122-5a251847c3e5.png)

### What does the proposed API look like?
A setting on axis or series level which defines if space for empty values is preserved

Would be great to get some feedback on that :)

**Comment by Ovilia** [comment] 2019-09-26 08:24
Duplicate of #9899 .

**Closed** 2019-09-26 08:24 UTC
Labels: duplicate
