### ISSUE TITLE
data的label没更新

### ISSUE THREAD

**Issue by oo2o** [apache/incubator-echarts#10529] opened 2019-05-23 07:58 UTC
### Version
4.2.1

### Reproduction link
[https://www.echartsjs.com/examples/editor.html?c=pictorialBar-spirit](https://www.echartsjs.com/examples/editor.html?c=pictorialBar-spirit)

### Steps to reproduce
打开页面可以直接看到图表右边的label数值一直没有更新

### What is expected?
右边的label数据会实时更新

### What is actually happening?
初始化值是多少就是多少

**Comment by susiwen8** [comment] 2019-05-23 12:11
Actually this was caused by zrender
https://github.com/ecomfe/zrender/blob/master/src/graphic/helper/text.js#L136
I'm try to figure out why __dirtyText is false

**Comment by oo2o** [comment] 2019-05-24 01:15
thank you for very mach

**Comment by susiwen8** [comment] 2019-05-24 01:21
@oo2o Actually, It's little hard to focus on debugging, coz your chart is so cute and moxing, I can't take my eye of it. Hahahaha

**Comment by Ovilia** [comment] 2019-05-24 03:22
Duplicate of #9532

**Comment by Ovilia** [comment] 2019-05-24 03:23
I'm going to close this issue. Please follow #9532 and discuss there.

**Closed by Ovilia** 2019-05-24 03:23 UTC
Labels: bug, pending, waiting-for-help
