### ISSUE TITLE
sublink无效

### ISSUE THREAD

**Issue by leohazy** [apache/incubator-echarts#12841] opened 2020-06-22 06:32 UTC
### Version
4.8.0

#### 1. sublink not work
the sublink cannot open ，but title link function well。such as the example in <https://echarts.apache.org/examples/zh/editor.html?c=map-HK>， sublink is not work，if change to link，function well，after this ,change to sublink again, sublink can work。

副标题链接无法打开，改成主标题链接则可以打开，此时再改为副标题链接则可以正常打开。
#### 2. 'www.xxxx' link not work
in the case <https://echarts.apache.org/examples/zh/editor.html?c=map-HK>,set the sublink to <www.baidu.com>,the sublink refer to <https://echarts.apache.org/examples/zh/undefined>,change sublink to link, it refer to <https://echarts.apache.org/examples/zh/www.baidu.com>. if set the link to <http://www.baidu.com>,funtion well。

如果把上述例子中的链接改为<www.baidu.com>时，sublink改为link的时候仍然无法打开，会跳转到<https://echarts.apache.org/examples/zh/www.baidu.com>，但是改为<http://www.baidu.com>，则可以正常跳转

### What is expected?
click sublink to jump to the specific link

### What is actually happening?
jump to an undefined page

**Comment by plainheart** [comment] 2020-06-22 06:43
`sublink` does not work is indeed a bug, but maybe `www.xxx` is not a bug. 
This feature uses `window.open` to open the links, if no protocol is specified for url, the browser will open it by current context path.

**Comment by leohazy** [comment] 2020-06-22 06:50
> It is indeed a bug that `sublink` does not work, but `www.xxx` may be not.
> This feature uses `window.open` to open the links, if no protocol is specified for url, the browser will open it by current context path.

got it ,thx! hope fix this sublink bug

**Comment by plainheart** [comment] 2020-06-22 07:03
Thanks for your reporting. It has been fixed in #12842.

**Closed** 2020-06-22 07:08 UTC
Labels: bug, en
